language: kotlin
jdk:
    - openjdk11

branches:
    only:
        - master

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
    - zip -r springboot2-davinci-webservice *
    - mkdir -p deploy
    - mv springboot2-davinci-webservice.zip deploy/springboot2-davinci-webservice.zip
deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY

      bucket: springboot-davinci-build
      region: ap-northeast-2
      skip_cleanup: true
      acl: private
      local_dir: deploy
      wait-until-deployed: true

    - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY

      bucket: springboot-davinci-build
      key: springboot2-davinci-webservice.zip
      bundle_type: zip
      application: springboot2-davinci-webservice

      deployment_group: springboot2-davinci-webservice
      region: ap-northeast-2
      wait-until-deployed: true

notifications:
    email:
        recipients:
            - "본인 이메일"
